---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "users:1:1,notifications:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:29092,EXTERNALHOST://0.0.0.0:9093,INTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,EXTERNALHOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,EXTERNALHOST://host.docker.internal:9093,INTERNAL://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  datagen:
    image: confluentinc/ksql-examples
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-x", "ksql-datagen", "topic=users", "maxInterval=3000", "value-format=json", "bootstrap-server=kafka:9092", "quickstart=users"] 
 
